version: '3'
services:
  chainalytic-icon:
    build: .
    image: duyyudus/chainalytic-icon
    container_name: chainalytic-icon
    network_mode: host
    volumes:
      - /path/to/data/mainnet:/mainnet
      - .chainalytic_icon/cfg:/chainalytic_icon/cfg
      - .chainalytic_icon/network_name:/chainalytic_icon/network_name
    ports:
      - 5600:5600
