network_name: 'icon_mainnet'

citizen_node_endpoint: 'https://ctz.solidwallet.io'

aggregator_endpoint: 'localhost:5500'
provider_endpoint: 'localhost:5600'

chain_db_dir: ''
score_db_icondex_dir: ''
direct_db_access: 1

transforms:
  - contract_history

storage_dir: '.chainalytic_icon/{network_name}/db'

# E.g. ".chainalytic_icon/warehouse/stake_history_storage"
transform_storage_dir: '{storage_dir}/{transform_id}_storage'
transform_cache_dir: '{storage_dir}/{transform_id}_cache'

log_dir: '.chainalytic_icon/{network_name}/log'

# 10: DEBUG
# 20: INFO
# 30: WARNING
# 40: ERROR
# 50: CRITICAL
log_level: 30